version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mail-schedule-db
    volumes:
      - pgdata:/data/postgres
    ports:
      - '5433:5432'

  api:
    container_name: mail-schedule-nestjs-api
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  pgdata:
    driver: local